# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teorema', '0002_um'),
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=25)),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.CharField(max_length=300)),
                ('note', models.TextField(max_length=800)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.CategoriaArticolo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoMagazzinoArticolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True)),
                ('quantita', models.DecimalField(decimal_places=4, max_digits=12)),
                ('movimento', models.CharField(choices=[('1', 'Carico'), ('2', 'Scarico')], max_length=7)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazzino.Articolo')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.UM')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoMagazzinoProdotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True)),
                ('quantita', models.DecimalField(decimal_places=4, max_digits=12)),
                ('movimento', models.CharField(choices=[('1', 'Carico'), ('2', 'Scarico')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.CharField(max_length=300, null=True)),
                ('note', models.TextField(max_length=800, null=True)),
                ('prezzo_netto', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('valuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teorema.Valuta')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='movimentomagazzinoprodotto',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazzino.Prodotto'),
        ),
        migrations.AddField(
            model_name='movimentomagazzinoprodotto',
            name='um',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.UM'),
        ),
    ]
