# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('ragione_sociale', models.CharField(max_length=40)),
                ('tipologia', models.CharField(choices=[('1', 'Azienda'), ('2', 'Privato')], default='2', max_length=12)),
                ('citta', models.CharField(max_length=30)),
                ('indirizzo', models.CharField(max_length=35)),
                ('indirizzo_n', models.CharField(max_length=6)),
                ('cap', models.CharField(max_length=12)),
                ('partita_iva', models.CharField(max_length=15)),
                ('codice_fiscale', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('cellulare', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=25)),
                ('mailpec', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=40)),
                ('citta', models.CharField(max_length=30)),
                ('indirizzo', models.CharField(max_length=35)),
                ('indirizzo_n', models.CharField(max_length=6)),
                ('cap', models.CharField(max_length=12)),
                ('partita_iva', models.CharField(max_length=15)),
                ('codice_fiscale', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('cellulare', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=25)),
                ('mailpec', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('valore', models.DecimalField(decimal_places=4, max_digits=6)),
                ('percentuale', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('nome_breve', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Nazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('nome_breve', models.CharField(max_length=5)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('nome_breve', models.CharField(max_length=5)),
                ('simbolo', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='nazione',
            name='valuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Valuta'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='lingua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Lingua'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='nazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Nazione'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='valuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Valuta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lingua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Lingua'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Nazione'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Valuta'),
        ),
    ]
