# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teorema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
    ]
