# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teorema', '0002_um'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoDiCorso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifica', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnoScolastico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('inizio', models.DateField()),
                ('fine', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipologia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoDiCorso')),
                ('anno_scolatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoScolastico')),
            ],
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.CharField(max_length=300)),
                ('tipologia', models.CharField(choices=[('1', 'DDF'), ('2', 'Extra Obbligo'), ('3', 'Specializzazione'), ('4', 'Formazione Continua')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insegnante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('costo_orario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Valuta')),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Cliente')),
                ('anno_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoDiCorso')),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoScolastico')),
            ],
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Classe')),
                ('insegnante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Insegnante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PianoDiStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Corso')),
            ],
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Cliente')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Insegnante')),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Lezione')),
            ],
        ),
        migrations.CreateModel(
            name='SuperamentoAnno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Cliente')),
                ('anno_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoDiCorso')),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoScolastico')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('voto', models.DecimalField(decimal_places=1, max_digits=4)),
                ('alunno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teorema.Cliente')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Insegnante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='lezione',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Materia'),
        ),
        migrations.AddField(
            model_name='classe',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Corso'),
        ),
        migrations.AddField(
            model_name='annodicorso',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.Corso'),
        ),
        migrations.AddField(
            model_name='annodicorso',
            name='precedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corsi.AnnoDiCorso'),
        ),
    ]
